-- =============================================================================
-- Migration 010: Re-repair SQLx migration checksums (v2)
--
-- WHY THIS EXISTS:
--   Migration 009 was authored with checksums computed from an earlier version
--   of the migration files (different line-endings / content).  Once migration
--   009 ran it wrote those stale checksums into _sqlx_migrations, causing every
--   subsequent startup to abort with:
--       "migration XXXXXXXX was previously applied but has been modified"
--
--   This migration replaces every stored checksum with the SHA-384 of the
--   CURRENT file bytes on disk (computed 2026-05-28 via PowerShell
--   [IO.File]::ReadAllBytes → [Security.Cryptography.SHA384]::Create()).
--
-- CHECKSUMS VERIFIED AGAINST CURRENT FILE BYTES — DO NOT EDIT THIS FILE.
-- =============================================================================

UPDATE _sqlx_migrations
SET checksum = decode('8d4e8b3c57a9ed7ffb571fc47bb5313823b2a326df03f8d19ce6489dfdac6ca9e9d3e3f111b64113435d00336bb33cfa', 'hex')
WHERE version = 20250101000001;

UPDATE _sqlx_migrations
SET checksum = decode('fbd34b4db216ce4cae291ad6b0328e5dd4c0539a4309e1fdc6e940202609668cfc10ae814682a4c7024e03b0efb6a910', 'hex')
WHERE version = 20250101000002;

UPDATE _sqlx_migrations
SET checksum = decode('ebd26e87b4a0789c687d434f91d1297ce2aa1dd1c78dcbc3692c5f56a5e9d107d2508900bc2ab3ded86d136e2cc21529', 'hex')
WHERE version = 20250101000003;

UPDATE _sqlx_migrations
SET checksum = decode('31828954ebec267d44edb60ad5ee2949ac573a578402b88399d71bb82e0a7455e7f82ba936da72bbe8c5dd2ebdf82cd0', 'hex')
WHERE version = 20250101000004;

UPDATE _sqlx_migrations
SET checksum = decode('8b789903a4de31d3a839aa6fbce26e542cdc3369093d6b6e7e98ca068214f3897a4f758fe8394021d22522c25035033e', 'hex')
WHERE version = 20250101000005;

UPDATE _sqlx_migrations
SET checksum = decode('1f039dba6c648a10ea3fd3e4bd5fa82a151f61bd42dc9a9cf6e46bbbccc984e6f953ce13218921786a64b54dc2129683', 'hex')
WHERE version = 20250101000006;

UPDATE _sqlx_migrations
SET checksum = decode('8c417288ae1a82362c8253cc5d06f696758fc1e739a66e9e6581e364ce6d1e19adeed1fb375d99a8ea1d0b86f1ff6922', 'hex')
WHERE version = 20250101000007;

UPDATE _sqlx_migrations
SET checksum = decode('1b58cd95e80f840b94f0b158e9ef29deb6d48b39d22c6d5a0991c2de35d5e2278bee459e2343d39676e8fac5d914b98d', 'hex')
WHERE version = 20250101000008;
